spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/task-ms

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


server:
  servlet:
    context-path: /task-ms
